// Mensagens de retorno das ações, centralizadas. As actions redirecionam com
// ?ok=<código> ou ?erro=<código>; o toast global (ActionToast) lê o código aqui
// e mostra a mensagem, em qualquer tela do app. Um só lugar para revisar textos.

export const OK_MESSAGES: Record<string, string> = {
  "1": "Feito.",
  cadastrado: "Cliente cadastrado. O projeto entrou na primeira etapa do funil.",
  cliente: "Dados do cliente salvos.",
  contato: "Contato salvo.",
  contrato: "Contrato salvo. O marco contratual foi recalculado.",
  "contrato-anexado": "Contrato anexado. Os dados foram mantidos.",
  "contrato-atualizado": "Cadastro atualizado a partir do contrato.",
  cronograma: "Cronograma importado.",
  restaurado: "Cliente restaurado.",
  prazo: "Prazo salvo.",
  etapa: "Etapa salva.",
  "etapa-criada": "Etapa criada.",
  "etapa-removida": "Etapa removida.",
  "etapa-movida": "Etapas reordenadas.",
};

export const ERRO_MESSAGES: Record<string, string> = {
  arquivo: "Selecione um arquivo válido.",
  "arquivo-grande": "Arquivo muito grande (máximo 4 MB).",
  "arquivo-tipo": "Tipo de arquivo não aceito.",
  "auto-exclusao": "Você não pode remover a própria conta.",
  campos: "Preencha os campos obrigatórios.",
  categoria: "Selecione uma categoria.",
  checklist: "Conclua o checklist da etapa antes de avançar.",
  "cnpj-duplicado": "Já existe um cliente cadastrado com esse CNPJ.",
  consultor: "Selecione um consultor válido.",
  contato: "Não foi possível salvar o contato.",
  "contrato-duplicado": "Esse contrato já está cadastrado.",
  "contrato-ilegivel": "Não foi possível ler o contrato. Verifique o PDF.",
  credenciais: "Email ou senha incorretos.",
  dominio: "Use um email do domínio autorizado.",
  "email-existente": "Já existe uma conta com esse email.",
  "ja-ativada": "Esta conta já foi ativada.",
  "nao-encontrado": "Registro não encontrado.",
  papel: "Papel inválido.",
  pendente: "Sua conta está aguardando liberação de acesso.",
  permissao: "Você não tem permissão para esta ação.",
  "permissao-papel": "Você não pode atribuir esse papel.",
  "permissao-produto": "Você só pode agir no seu próprio produto.",
  planilha: "Não foi possível ler a planilha.",
  "planilha-invalida": "Planilha inválida.",
  "planilha-tipo": "Envie uma planilha no formato aceito.",
  produto: "Selecione um produto válido.",
  "produto-invalido": "Produto inválido.",
  "produto-obrigatorio": "Selecione o produto.",
  "razao-social": "Informe a razão social.",
  recusado: "Seu acesso foi recusado.",
  "sem-projeto": "O cliente não tem projeto para vincular.",
  "sem-senha": "Defina uma senha para continuar.",
  "senha-curta": "A senha é muito curta.",
  status: "Status inválido.",
  titulo: "Informe o título.",
  token: "Convite inválido, já usado ou expirado. Peça para reenviarem.",
  ultima: "Não é possível remover a última etapa.",
  "ultima-diretoria": "Não é possível remover a última pessoa da diretoria.",
};
